3.0.0
microsoft/powerbi-visuals-webpack-plugin pull request #70
Opened 2021-11-09 11:41 UTC by Demonkratiy

* refactored assets compilation due to latest webpack rules
* added non-personal environment logging

2021-11-10 13:47 UTC, uve requested changes

2021-11-10 13:47 UTC, uve commented on templates/package-json-template.js
> +					"tools version": `${templateOptions.environment.toolsVersion}`,
do not use whitespaces in the name

2021-11-10 13:47 UTC, uve commented on templates/package-json-template.js
> +					"operating system": {
rename to os

2021-11-10 13:47 UTC, uve commented on templates/package-json-template.js
> +			: "is not defined",
keep 'undefined'

2021-11-10 14:57 UTC, Demonkratiy commented on templates/package-json-template.js
> +					"tools version": `${templateOptions.environment.toolsVersion}`,
renamed

2021-11-10 14:57 UTC, Demonkratiy commented on templates/package-json-template.js
> +					"operating system": {
renamed

2021-11-10 14:57 UTC, Demonkratiy commented on templates/package-json-template.js
> +			: "is not defined",
renamed

2021-11-18 13:41 UTC, uve approved these changes

2021-11-18 13:42 UTC, merged